services:
  db:
    image: postgres:latest
    container_name: stocklyn_dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=uday
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stocklyn
    volumes:
      - postgres-data:/var/lib/postgresql/data/
volumes:
  postgres-data:
