name: Deploy to VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: maalelo
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ""
          script: bash /home/maalelo/deploy.sh
