name: Deploy to VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: trazor
          key: ${{ secrets.SSH_PRIVATE_KEY_TRAZOR }}
          passphrase: ""
          script: bash /home/trazor/deploy.sh

//test